apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mlops

resources:
- namespaces.yaml
- pvcs.yaml
- postgres.yaml
- minio.yaml
- mlflow.yaml
- jupyterhub.yaml
- ingress.yaml

patches:
- target:
    kind: Namespace
    name: mlops
  patch: |-
    - op: add
      path: /metadata/labels
      value:
        app.kubernetes.io/part-of: mlops-lab